approvedGitRepositories:
  - "**"

compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

enableTelemetry: 0

nodeLinker: node-modules

# Age gate can be bypassed by setting YARN_NPM_MINIMAL_AGE_GATE=0 env variable.
npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.1.cjs
